DATABASE_URL_POOLED = "postgresql://neondb_owner:npg_jypET4QU1SLx@ep-hidden-wave-a77auoyp-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require" 

JSONBIN_BIN_ID = "6ab6020eac6210605af342cf"
JSONBIN_API_KEY = "$2a$10$w.dBKLVP2/BjID/Gs0jtY.ZUBIaiXcjImK8n.UOzZLwZryxyA5Ggq"

[auth]
cookie_key = "LeVzjKNQ4YFfiIUhLqvjXL0jE-j0eJrrLaJwA96mUEE"
cookie_days = 90

[auth.users]
davidwilliamriley = "$2b$12$wDAmITDVjj0/kzBCM9juH.jBteC98qdyMJ0roohfJOf3yYllcOVJO"